feeds.update({
    "##covid-19": (
        {
            "https://github.com/ljl-covid/links/commits/master.atom": "##covid-19 resources*",
            "https://api.zotero.org/groups/4391070/items/top?direction=desc&format=atom&sort=dateAdded&limit=20": "##covid-19 Zotero group*",
            "https://covidreference.com/feed": "COVID Reference*",
            "https://erictopol.substack.com/feed": "Eric Topol on Substack",
            "https://cmmid.github.io/feed.xml": "CMMID Repository*",
            "http://ljlbox:85/?action=display&bridge=WHO&format=Atom": "WHO Outbreaks",
            "http://ljlbox:85/?action=display&bridge=Twitter&context=By+list+ID&listid=1326305739569324036&filter=&format=Atom": "COVID on Twitter",
            "https://www.medicinenet.com/rss/dailyhealth.xml": "MedicineNet",
            "https://www.contagionlive.com/rss": "Contagion Live",
            "https://www.pfizer.com/newsfeed": "Pfizer",
            "https://investors.biontech.de/rss/news-releases.xml": "BioNTech",
            "http://www.jnj.com/rss-feed/all": "Johnson&Johnson",
            "https://ir.novavax.com/press-releases?pagetemplate=rss&category=2": "Novavax",
            "https://covid19.trackvaccines.org/vaccines/feed/": "COVID19 Vaccine Tracker*",
            "https://www.ncbi.nlm.nih.gov/research/coronavirus-api/feed?": "LitCovid*",
            "https://outbreak.info/blog/rss": "outbreak.info blog*",
            "https://github.com/NAalytics/Assemblies-of-putative-SARS-CoV2-spike-encoding-mRNA-sequences-for-vaccines-BNT-162b2-and-mRNA-1273/commits/main.atom": "mRNA sequences",
            "https://www.ema.europa.eu/en/individual-human-medicine.xml/131631": "EMA: Comirnaty (vaccine)",
            "https://www.ema.europa.eu/en/individual-human-medicine.xml/132778": "EMA: Vaxzevria (AstraZeneca)",
            "https://www.ema.europa.eu/en/individual-human-medicine.xml/127227": "EMA: Veklury (Remdesivir)",
            "https://feeds.feedburner.com/Pnas-RssFeedOfEarlyEditionArticles?format=xml": "PNAS",
            "https://www.fda.gov/about-fda/contact-fda/stay-informed/rss-feeds/press-releases/rss.xml": "FDA Press Releases",
            "https://www.ema.europa.eu/en/whats-new.xml": "EMA: What's new",
            "https://www.ema.europa.eu/en/news.xml": "EMA: News and press releases",
            "https://www.ema.europa.eu/en/human-medicine-new.xml": "EMA: Human medicine assessment reports",
            "https://clinicaltrials.gov/ct2/results/rss.xml?rcv_d=2&lup_d=&sel_rss=new14&cond=Covid19&count=100": "ClinicalTrials.gov*",
            "https://sciencebasedmedicine.org/feed/": "Science-Based Medicine",
            "https://feeds.npr.org/816541428/rss.xml": "NPR*",
            "https://feeds.npr.org/1007/rss.xml": "NPR Science",
            "https://www.ecdc.europa.eu/en/taxonomy/term/2942/feed": "ECDC*",
            "https://insight.jci.org/rss": "JCI Insight",
            "https://www.sciencedaily.com/rss/health_medicine.xml": "Science Daily",
            "https://journals.plos.org/plosmedicine/feed/atom": "PLOS Medicine",
            "https://www.cidrap.umn.edu/news/178636/rss": "CIDRAP*",
            "https://www.virology.ws/feed": "Virology.ws",
            "http://twiv.microbeworld.libsynpro.com/twiv": "This Week In Virology*",
            "https://globalhealth.washington.edu/news/feed": "University of Washington",
            "https://journals.plos.org/plosmedicine/feed/atom": "PLOS",
            "https://pubmed.ncbi.nlm.nih.gov/rss/search/1-wHEn2QPyP8TjeekoeFt94FSgjI-yG-hiXm2yeurI8n5CAgt-/?limit=20&utm_campaign=pubmed-2&fc=20200904175635": "PubMed*",
            "https://www.statnews.com/feed/": "StatNews",
            "https://medicalxpress.com/rss-feed/tags/coronavirus/": "Medical Xpress*",
            "https://retractionwatch.com/feed/": "Retraction Watch",
            "https://directorsblog.nih.gov/feed": "NIH Director's blog",
            "http://feeds.nature.com/nature/rss/current": "Nature",
            "http://www.nature.com/nm/current_issue/rss/": "Nature Medicine",
            "https://www.nature.com/subjects/vaccines.atom": "Nature Vaccines",
            "https://www.eurekalert.org/rss.xml": "EurekAlert!",
            "https://tools.cdc.gov/api/v2/resources/media/403372.rss": "CDC (old)*",
            "https://tools.cdc.gov/api/v2/resources/media/404952.rss": "CDC*",
            "https://feeds.feedburner.com/who/euro/rss/en": "WHO Euro",
            "https://www.who.int/feeds/entity/mediacentre/news/en/rss.xml": "WHO",
#            "https://old.reddit.com/r/worldnews/rising.rss?limit=3": "r/WorldNews",
            "https://old.reddit.com/r/Coronavirus/hot.rss?limit=4": "r/Coronavirus*",
            "https://www.reddit.com/r/COVID19/hot.rss?limit=4": "r/COVID19*",
            "https://feeds.feedburner.com/RsoeEdis-Ebhwm?format=xml": "RSOE EDIS",
#            "https://old.reddit.com/user/LjLies/m/covid19ljl.rss?limit=5": "Reddit (test)*",
            "https://old.reddit.com/r/science/.rss": "r/Science",
            "https://feeds.newscientist.com/health": "New Scientist",
            "https://feeds.bbci.co.uk/news/health/rss.xml": "BBC Health",
            "http://feeds.arstechnica.com/arstechnica/index": "Ars Technica",
            "http://rss.sciam.com/sciam/health-and-medicine": "Scientific American",
            "https://www.thelancet.com/rssfeed/lancet_current.xml": "The Lancet",
            "https://www.thelancet.com/rssfeed/lancet_online.xml": "The Lancet (Online)",
            "https://www.cdc.gov/ncidod/eid/rss/upcoming.xml": "CDC EIDJ",
            "http://feeds.bmj.com/bmj/recent": "BMJ",
            "https://bmjopen.bmj.com/rss/current.xml": "BMJ Open",
            "https://stm.sciencemag.org/rss/current.xml": "ScienceMag",
            "https://www.sciencemag.org/coronavirus-news-api.xml": "ScienceMag COVID-19 news*",
            "https://www.sciencenews.org/feed": "ScienceNews",
            "https://www.science.org/blogs/pipeline/feed": "In The Pipeline*",
            "https://www.theatlantic.com/feed/channel/health/": "The Atlantic",
            "https://podcast.nejm.org/nejm_audio_interview.xml": "NEJM podcasts",
            "https://search.nejm.org/search?cnt=20&start_month=3&start_year=2010&w=*&restrict=doctype%3Aarticle&srt=0&isort=date&ts=rss&af=topic:18": "NEJM Infectious Disease",
            "https://search.nejm.org/search?cnt=20&start_month=3&start_year=2010&w=*&restrict=doctype%3Aarticle&srt=0&isort=date&ts=rss&af=topic:13": "NEJM Genetics",
            "https://search.nejm.org/search?cnt=20&start_month=3&start_year=2010&w=*&restrict=doctype%3Aarticle&srt=0&isort=date&ts=rss&af=topic:24": "NEJM Health Policy",
            "https://jamanetwork.com/rss/site_3/mostReadArticles.xml": "JAMA",
            "https://www.medpagetoday.com/rss/headlines.xml": "MedPageToday",
            "https://rssfeeds.webmd.com/rss/rss.aspx?RSSSource=RSS_PUBLIC": "WebMD",
            "https://www.ilsole24ore.com/rss/salute.xml": "Il Sole 24 Ore",
            "http://feeds.propublica.org/propublica/main": "ProPublica",
            "https://virological.org/c/novel-2019-coronavirus/33.rss": "Virological.org*",
            "https://virological.org/posts.rss": "Virological.org: Latest posts",
            "https://virological.org/latest.rss": "Virological.org: Latest topics",
            "https://ourworldindata.org/atom.xml": "Our World In Data",
            "https://promedmail.org/feed/": "ProMED-mail",
            "https://api.quantamagazine.org/feed/": "Quanta Magazine",
            "https://www.politico.eu/feed": "Politico",
            "http://feeds.feedburner.com/euronews/en/europa/": "EuroNews",
            "https://www.isdbweb.org/feed": "ISDB",
        },
        7,
        None,
        r"(coronavirus|COVID|pandemic|epidemic|SARS|face mask|sanitizer|new cases|Wuhan|Hubei|Lombardy|Lombardia|Moderna|quarantena|quarantine|isolation|lockdown|swab|Milan|\btests\b|\bICU\b|antibod|pcr|dexamethasone|remdesivir|chloroquine|hcq|\bPPE\b|n95|aerosol|airborne|triage|reopen|il-6|il-8|anti-tnf|cytokine|vaccin|biontech|pfizer|astrazeneca|sanofi|sputnik v|sinovac|sinopharm|curevac|coronavac|B117|B.1.1.7|B.1.1.529|B11529|UK variant|SA variant|variants? of concern|d614g|e484k|n501y|s477g|s477n|p681h|n440k|green pass|plasminogen|\btpa\b|delta variant|beta variant|lambda variant|uk variant|omicron|BA\.1|BA\.2|indian variant|brazilian variant|B.1.617.2|AY.3)",
    ),
    "##covid-ticker": (
        {
            "https://clinicaltrials.gov/ct2/results/rss.xml?rcv_d=2&lup_d=&sel_rss=new14&cond=Covid19&count=100": "ClinicalTrials.gov*",
            "http://ljlbox:85/?action=display&bridge=Twitter&context=By+list+ID&listid=1461764983533064202&filter=&format=Atom": "COVID on Twitter",
            "http://ljlbox:85/?action=display&bridge=Twitter&context=By+list+ID&listid=1384523560320962561&filter=&nopic=on&noimg=on&noimgscaling=on&format=Atom": "COVID list by @kevinwineinger",
            # "http://ljlbox:85/?action=display&bridge=Twitter&context=By+list+ID&listid=1257945421231554560&filter=&nopic=on&noimg=on&noimgscaling=on&format=Atom": "COVID list by @JavierECarpio",  # Removed as very verbose
            "https://en.wikipedia.org/w/index.php?title=Variants_of_SARS-CoV-2&feed=atom&action=history&hidebots=1&hideminor=1": "Variants of SARS-CoV-2 on Wikipedia",
            "https://en.wikipedia.org/w/index.php?title=Cluster_5&feed=atom&action=history": '"Cluster 5" on Wikipedia',
            "https://en.wikipedia.org/w/index.php?title=COVID-19_pandemic_in_Denmark&feed=atom&action=history": '"COVID-19 pandemic in Denmark" on Wikipedia',
            "https://en.wikipedia.org/w/index.php?title=COVID-19_pandemic_lockdowns&feed=atom&action=history&hideminor=1&hidebots=1": "Lockdowns from Wikipedia",
            "https://en.wikipedia.org/w/index.php?title=PF-07321332&feed=atom&action=history": "PF-07321332 (Paxlovid) on Wikipedia",
            "https://it.wikipedia.org/w/index.php?title=PF-07321332&feed=atom&action=history": "PF-07321332 (Paxlovid) sulla Wikipedia italiana",
            "https://en.wikipedia.org/w/index.php?title=SARS-CoV-2_Omicron_variant&feed=atom&action=history": "SARS-CoV-2 Omicron variant on Wikipedia",
            "http://twiv.microbeworld.libsynpro.com/twiv": "This Week In Virology*",
            "https://www.virology.ws/feed": "Virology.ws",
            "https://virological.org/c/novel-2019-coronavirus/33.rss": "Virological.org*",
            "https://virological.org/posts.rss": "Virological.org: Latest posts",
            "https://virological.org/latest.rss": "Virological.org: Latest topics",
            "https://covid19.trackvaccines.org/vaccines/feed/": "COVID19 Vaccine Tracker*",
            "http://www.gazzettaufficiale.it/rss/SG": "Gazzetta Ufficiale italiana",
            "https://www.ilsole24ore.com/rss/salute.xml": "Il Sole 24 Ore",
            "https://www.regione.lombardia.it/wps/wcm/connect/DisegnoPRL/FeedRSS/stFeedRssLombardiaNotizie": "Lombardia Notizie",
            "https://www.regione.lombardia.it/wps/wcm/connect/DisegnoPRL/FeedRSS/stFeedRssLombardiaNotizie": "Lombardia Provvedimenti",

        },
        7,
        None,
        None,
    ),
    "##covid-news": (
        {
            "https://covidreference.com/feed": "COVID Reference*",
            "https://cmmid.github.io/feed.xml": "CMMID Repository*",
            "http://ljlbox:85/?action=display&bridge=WHO&format=Atom": "WHO Outbreaks",
            "https://www.medicinenet.com/rss/dailyhealth.xml": "MedicineNet",
            "https://www.contagionlive.com/rss": "Contagion Live",
            "https://www.pfizer.com/newsfeed": "Pfizer",
            "https://investors.biontech.de/rss/news-releases.xml": "BioNTech",
            "http://www.jnj.com/rss-feed/all": "Johnson&Johnson",
            "https://ir.novavax.com/press-releases?pagetemplate=rss&category=2": "Novavax",
            "https://covid19.trackvaccines.org/vaccines/feed/": "COVID19 Vaccine Tracker*",
            "https://www.ncbi.nlm.nih.gov/research/coronavirus-api/feed?": "LitCovid*",
            "https://outbreak.info/blog/rss": "outbreak.info blog*",
            "https://github.com/NAalytics/Assemblies-of-putative-SARS-CoV2-spike-encoding-mRNA-sequences-for-vaccines-BNT-162b2-and-mRNA-1273/commits/main.atom": "mRNA sequences",
            "https://www.ema.europa.eu/en/individual-human-medicine.xml/131631": "EMA: Comirnaty (vaccine)",
            "https://www.ema.europa.eu/en/individual-human-medicine.xml/132778": "EMA: Vaxzevria (AstraZeneca)",
            "https://feeds.feedburner.com/Pnas-RssFeedOfEarlyEditionArticles?format=xml": "PNAS",
            "https://www.fda.gov/about-fda/contact-fda/stay-informed/rss-feeds/press-releases/rss.xml": "FDA Press Releases",
            "https://www.ema.europa.eu/en/whats-new.xml": "EMA: What's new",
            "https://www.ema.europa.eu/en/news.xml": "EMA: News and press releases",
            "https://www.ema.europa.eu/en/human-medicine-new.xml": "EMA: Human medicine assessment reports",
            "https://sciencebasedmedicine.org/feed/": "Science-Based Medicine",
            "https://feeds.npr.org/816541428/rss.xml": "NPR*",
            "https://feeds.npr.org/1007/rss.xml": "NPR Science",
            "https://indianexpress.com/section/world/feed/": "The Indian Express",
            "https://indianexpress.com/section/lifestyle/feed/": "The Indian Express (Health)",
            "https://www.ecdc.europa.eu/en/taxonomy/term/2942/feed": "ECDC*",
            "https://insight.jci.org/rss": "JCI Insight",
            "https://www.sciencedaily.com/rss/health_medicine.xml": "Science Daily",
            "https://journals.plos.org/plosmedicine/feed/atom": "PLOS Medicine",
            "https://www.cidrap.umn.edu/news/178636/rss": "CIDRAP*",
            "https://globalhealth.washington.edu/news/feed": "University of Washington",
            "https://journals.plos.org/plosmedicine/feed/atom": "PLOS",
            "https://pubmed.ncbi.nlm.nih.gov/rss/search/1-wHEn2QPyP8TjeekoeFt94FSgjI-yG-hiXm2yeurI8n5CAgt-/?limit=20&utm_campaign=pubmed-2&fc=20200904175635": "PubMed*",
            "https://www.statnews.com/feed/": "StatNews",
            "https://medicalxpress.com/rss-feed/tags/coronavirus/": "Medical Xpress*",
            "https://retractionwatch.com/feed/": "Retraction Watch",
            "https://directorsblog.nih.gov/feed": "NIH Director's blog",
            "http://feeds.nature.com/nature/rss/current": "Nature",
            "http://www.nature.com/nm/current_issue/rss/": "Nature Medicine",
            "https://www.nature.com/subjects/vaccines.atom": "Nature Vaccines",
            "https://www.eurekalert.org/rss.xml": "EurekAlert!",
            "https://tools.cdc.gov/api/v2/resources/media/403372.rss": "CDC (old)*",
            "https://tools.cdc.gov/api/v2/resources/media/404952.rss": "CDC*",
            "https://feeds.feedburner.com/who/euro/rss/en": "WHO Euro",
            "https://www.who.int/feeds/entity/mediacentre/news/en/rss.xml": "WHO",
            "https://old.reddit.com/r/worldnews/rising.rss?limit=3": "r/WorldNews",
            "https://feeds.feedburner.com/RsoeEdis-Ebhwm?format=xml": "RSOE EDIS",
            "http://feeds.propublica.org/propublica/main": "ProPublica",
            "https://ourworldindata.org/atom.xml": "Our World In Data",
            "https://promedmail.org/feed/": "ProMED-mail",
            "https://api.quantamagazine.org/feed/": "Quanta Magazine",
            "https://www.politico.eu/feed": "Politico",
            "http://feeds.feedburner.com/euronews/en/europa/": "EuroNews",
            "https://www.isdbweb.org/feed": "ISDB",
            "https://feeds.newscientist.com/health": "New Scientist",
            "https://feeds.bbci.co.uk/news/health/rss.xml": "BBC Health",
            "http://feeds.arstechnica.com/arstechnica/index": "Ars Technica",
            "http://rss.sciam.com/sciam/health-and-medicine": "Scientific American",
            "https://www.thelancet.com/rssfeed/lancet_current.xml": "The Lancet",
            "https://www.thelancet.com/rssfeed/lancet_online.xml": "The Lancet (Online)",
            "https://www.cdc.gov/ncidod/eid/rss/upcoming.xml": "CDC EIDJ",
            "http://feeds.bmj.com/bmj/recent": "BMJ",
            "https://bmjopen.bmj.com/rss/current.xml": "BMJ Open",
            "https://stm.sciencemag.org/rss/current.xml": "ScienceMag",
            "https://www.sciencemag.org/coronavirus-news-api.xml": "ScienceMag COVID-19 news*",
            "https://www.sciencenews.org/feed": "ScienceNews",
            "https://www.science.org/blogs/pipeline/feed": "In The Pipeline*",
            "https://www.theatlantic.com/feed/channel/health/": "The Atlantic",
            "https://podcast.nejm.org/nejm_audio_interview.xml": "NEJM podcasts",
            "https://search.nejm.org/search?cnt=20&start_month=3&start_year=2010&w=*&restrict=doctype%3Aarticle&srt=0&isort=date&ts=rss&af=topic:18": "NEJM Infectious Disease",
            "https://search.nejm.org/search?cnt=20&start_month=3&start_year=2010&w=*&restrict=doctype%3Aarticle&srt=0&isort=date&ts=rss&af=topic:13": "NEJM Genetics",
            "https://search.nejm.org/search?cnt=20&start_month=3&start_year=2010&w=*&restrict=doctype%3Aarticle&srt=0&isort=date&ts=rss&af=topic:24": "NEJM Health Policy",
            "https://jamanetwork.com/rss/site_3/mostReadArticles.xml": "JAMA",
            "https://www.medpagetoday.com/rss/headlines.xml": "MedPageToday",
            "https://rssfeeds.webmd.com/rss/rss.aspx?RSSSource=RSS_PUBLIC": "WebMD",
            "https://old.reddit.com/r/science/.rss": "r/Science",
            "https://old.reddit.com/r/Coronavirus.rss?limit=3": "r/Coronavirus*",
            "https://old.reddit.com/user/LjLies/m/covid19ljl.rss?limit=5": "Reddit (test)*",
        },
        7,
        None,
        r"(coronavirus|COVID|pandemic|epidemic|SARS|face mask|sanitizer|new cases|Wuhan|Hubei|Lombardy|Lombardia|Moderna|quarantena|quarantine|isolation|lockdown|swab|Milan|\btests\b|\bICU\b|antibod|pcr|dexamethasone|remdesivir|chloroquine|hcq|\bPPE\b|n95|aerosol|airborne|triage|reopen|il-6|il-8|anti-tnf|cytokine|vaccin|biontech|pfizer|astrazeneca|sanofi|sputnik v|sinovac|sinopharm|curevac|coronavac|B117|B.1.1.7|B.1.1.529|B11529|UK variant|SA variant|variants? of concern|d614g|e484k|n501y|s477g|s477n|p681h|n440k|green pass|plasminogen|\btpa\b|delta variant|beta variant|lambda variant|uk variant|omicron|BA\.1|BA\.2|indian variant|brazilian variant|B.1.617.2|AY.3)",
    ),
})
